import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - generated by remix vite:build
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({ build });
