export const variants = {
  flex: "flex flex-1",
  base: {
    directions: [
      "flex-row",
      "flex-col",
      "flex-row-reverse",
      "flex-col-reverse",
      "flex-wrap",
      "flex-nowrap",
      "flex-wrap-reverse",
    ],
    shrink: ["shrink", "shrink-0"],
    grow: ["grow", "grow-0"],
    justifyContent: [
      "justify-normal",
      "justify-start",
      "justify-end",
      "justify-center",
      "justify-between",
      "justify-around",
      "justify-evenly",
      "justify-stretch",
    ],
    alignItems: [
      "items-stretch",
      "items-center",
      "items-start",
      "items-end",
      "items-baseline",
    ],
    alignSelf: [
      "self-auto",
      "self-start",
      "self-end",
      "self-center",
      "self-stretch",
      "self-baseline",
    ],
    wrap: ["flex-wrap", "flex-wrap-reverse", "flex-nowrap"],
  },
  medium: {
    directions: [
      "md:flex-row",
      "md:flex-col",
      "md:flex-row-reverse",
      "md:flex-col-reverse",
      "md:flex-wrap",
      "md:flex-nowrap",
      "md:flex-wrap-reverse",
    ],
    shrink: ["md:shrink", "md:shrink-0"],
    grow: ["md:grow", "md:grow-0"],
    justifyContent: [
      "md:justify-normal",
      "md:justify-start",
      "md:justify-end",
      "md:justify-center",
      "md:justify-between",
      "md:justify-around",
      "md:justify-evenly",
      "md:justify-stretch",
    ],
    alignItems: [
      "md:items-stretch",
      "md:items-center",
      "md:items-start",
      "md:items-end",
      "md:items-baseline",
    ],
    alignSelf: [
      "md:self-auto",
      "md:self-start",
      "md:self-end",
      "md:self-center",
      "md:self-stretch",
      "md:self-baseline",
    ],
    wrap: ["md:flex-wrap", "md:flex-wrap-reverse", "md:flex-nowrap"],
  },
  large: {
    directions: [
      "lg:flex-row",
      "lg:flex-col",
      "lg:flex-row-reverse",
      "lg:flex-col-reverse",
      "lg:flex-wrap",
      "lg:flex-nowrap",
      "lg:flex-wrap-reverse",
    ],
    shrink: ["lg:shrink", "lg:shrink-0"],
    grow: ["lg:grow", "lg:grow-0"],
    justifyContent: [
      "lg:justify-normal",
      "lg:justify-start",
      "lg:justify-end",
      "lg:justify-center",
      "lg:justify-between",
      "lg:justify-around",
      "lg:justify-evenly",
      "lg:justify-stretch",
    ],
    alignItems: [
      "lg:items-stretch",
      "lg:items-center",
      "lg:items-start",
      "lg:items-end",
      "lg:items-baseline",
    ],
    alignSelf: [
      "lg:self-auto",
      "lg:self-start",
      "lg:self-end",
      "lg:self-center",
      "lg:self-stretch",
      "lg:self-baseline",
    ],
    wrap: ["lg:flex-wrap", "lg:flex-wrap-reverse", "lg:flex-nowrap"],
  },
};
