export const variants = {
  medium: {
    neutral: [
      "lg:dark:border-neutral-100",
      "lg:dark:border-neutral-200",
      "lg:dark:border-neutral-300",
      "lg:dark:border-neutral-400",
      "lg:dark:border-neutral-500",
      "lg:dark:border-neutral-600",
      "lg:dark:border-neutral-700",
      "lg:dark:border-neutral-800",
      "lg:dark:border-neutral-900",
    ],
    stone: [
      "lg:dark:border-stone-100",
      "lg:dark:border-stone-200",
      "lg:dark:border-stone-300",
      "lg:dark:border-stone-400",
      "lg:dark:border-stone-500",
      "lg:dark:border-stone-600",
      "lg:dark:border-stone-700",
      "lg:dark:border-stone-800",
      "lg:dark:border-stone-900",
    ],
    slate: [
      "lg:dark:border-slate-100",
      "lg:dark:border-slate-200",
      "lg:dark:border-slate-300",
      "lg:dark:border-slate-400",
      "lg:dark:border-slate-500",
      "lg:dark:border-slate-600",
      "lg:dark:border-slate-700",
      "lg:dark:border-slate-800",
      "lg:dark:border-slate-900",
    ],
    gray: [
      "lg:dark:border-gray-100",
      "lg:dark:border-gray-200",
      "lg:dark:border-gray-300",
      "lg:dark:border-gray-400",
      "lg:dark:border-gray-500",
      "lg:dark:border-gray-600",
      "lg:dark:border-gray-700",
      "lg:dark:border-gray-800",
      "lg:dark:border-gray-900",
    ],
    zinc: [
      "lg:dark:border-zinc-100",
      "lg:dark:border-zinc-200",
      "lg:dark:border-zinc-300",
      "lg:dark:border-zinc-400",
      "lg:dark:border-zinc-500",
      "lg:dark:border-zinc-600",
      "lg:dark:border-zinc-700",
      "lg:dark:border-zinc-800",
      "lg:dark:border-zinc-900",
    ],
    red: [
      "lg:dark:border-red-100",
      "lg:dark:border-red-200",
      "lg:dark:border-red-300",
      "lg:dark:border-red-400",
      "lg:dark:border-red-500",
      "lg:dark:border-red-600",
      "lg:dark:border-red-700",
      "lg:dark:border-red-800",
      "lg:dark:border-red-900",
    ],
    orange: [
      "lg:dark:border-orange-100",
      "lg:dark:border-orange-200",
      "lg:dark:border-orange-300",
      "lg:dark:border-orange-400",
      "lg:dark:border-orange-500",
      "lg:dark:border-orange-600",
      "lg:dark:border-orange-700",
      "lg:dark:border-orange-800",
      "lg:dark:border-orange-900",
    ],
    amber: [
      "lg:dark:border-amber-100",
      "lg:dark:border-amber-200",
      "lg:dark:border-amber-300",
      "lg:dark:border-amber-400",
      "lg:dark:border-amber-500",
      "lg:dark:border-amber-600",
      "lg:dark:border-amber-700",
      "lg:dark:border-amber-800",
      "lg:dark:border-amber-900",
    ],
    yellow: [
      "lg:dark:border-yellow-100",
      "lg:dark:border-yellow-200",
      "lg:dark:border-yellow-300",
      "lg:dark:border-yellow-400",
      "lg:dark:border-yellow-500",
      "lg:dark:border-yellow-600",
      "lg:dark:border-yellow-700",
      "lg:dark:border-yellow-800",
      "lg:dark:border-yellow-900",
    ],
    lime: [
      "lg:dark:border-lime-100",
      "lg:dark:border-lime-200",
      "lg:dark:border-lime-300",
      "lg:dark:border-lime-400",
      "lg:dark:border-lime-500",
      "lg:dark:border-lime-600",
      "lg:dark:border-lime-700",
      "lg:dark:border-lime-800",
      "lg:dark:border-lime-900",
    ],
    green: [
      "lg:dark:border-green-100",
      "lg:dark:border-green-200",
      "lg:dark:border-green-300",
      "lg:dark:border-green-400",
      "lg:dark:border-green-500",
      "lg:dark:border-green-600",
      "lg:dark:border-green-700",
      "lg:dark:border-green-800",
      "lg:dark:border-green-900",
    ],
    emerald: [
      "lg:dark:border-emerald-100",
      "lg:dark:border-emerald-200",
      "lg:dark:border-emerald-300",
      "lg:dark:border-emerald-400",
      "lg:dark:border-emerald-500",
      "lg:dark:border-emerald-600",
      "lg:dark:border-emerald-700",
      "lg:dark:border-emerald-800",
      "lg:dark:border-emerald-900",
    ],
    teal: [
      "lg:dark:border-teal-100",
      "lg:dark:border-teal-200",
      "lg:dark:border-teal-300",
      "lg:dark:border-teal-400",
      "lg:dark:border-teal-500",
      "lg:dark:border-teal-600",
      "lg:dark:border-teal-700",
      "lg:dark:border-teal-800",
      "lg:dark:border-teal-900",
    ],
    cyan: [
      "lg:dark:border-cyan-100",
      "lg:dark:border-cyan-200",
      "lg:dark:border-cyan-300",
      "lg:dark:border-cyan-400",
      "lg:dark:border-cyan-500",
      "lg:dark:border-cyan-600",
      "lg:dark:border-cyan-700",
      "lg:dark:border-cyan-800",
      "lg:dark:border-cyan-900",
    ],
    sky: [
      "lg:dark:border-sky-100",
      "lg:dark:border-sky-200",
      "lg:dark:border-sky-300",
      "lg:dark:border-sky-400",
      "lg:dark:border-sky-500",
      "lg:dark:border-sky-600",
      "lg:dark:border-sky-700",
      "lg:dark:border-sky-800",
      "lg:dark:border-sky-900",
    ],
    blue: [
      "lg:dark:border-blue-100",
      "lg:dark:border-blue-200",
      "lg:dark:border-blue-300",
      "lg:dark:border-blue-400",
      "lg:dark:border-blue-500",
      "lg:dark:border-blue-600",
      "lg:dark:border-blue-700",
      "lg:dark:border-blue-800",
      "lg:dark:border-blue-900",
    ],
    indigo: [
      "lg:dark:border-indigo-100",
      "lg:dark:border-indigo-200",
      "lg:dark:border-indigo-300",
      "lg:dark:border-indigo-400",
      "lg:dark:border-indigo-500",
      "lg:dark:border-indigo-600",
      "lg:dark:border-indigo-700",
      "lg:dark:border-indigo-800",
      "lg:dark:border-indigo-900",
    ],
    violet: [
      "lg:dark:border-violet-100",
      "lg:dark:border-violet-200",
      "lg:dark:border-violet-300",
      "lg:dark:border-violet-400",
      "lg:dark:border-violet-500",
      "lg:dark:border-violet-600",
      "lg:dark:border-violet-700",
      "lg:dark:border-violet-800",
      "lg:dark:border-violet-900",
    ],
    purple: [
      "lg:dark:border-purple-100",
      "lg:dark:border-purple-200",
      "lg:dark:border-purple-300",
      "lg:dark:border-purple-400",
      "lg:dark:border-purple-500",
      "lg:dark:border-purple-600",
      "lg:dark:border-purple-700",
      "lg:dark:border-purple-800",
      "lg:dark:border-purple-900",
    ],
    fuchsia: [
      "lg:dark:border-fuchsia-100",
      "lg:dark:border-fuchsia-200",
      "lg:dark:border-fuchsia-300",
      "lg:dark:border-fuchsia-400",
      "lg:dark:border-fuchsia-500",
      "lg:dark:border-fuchsia-600",
      "lg:dark:border-fuchsia-700",
      "lg:dark:border-fuchsia-800",
      "lg:dark:border-fuchsia-900",
    ],
    pink: [
      "lg:dark:border-pink-100",
      "lg:dark:border-pink-200",
      "lg:dark:border-pink-300",
      "lg:dark:border-pink-400",
      "lg:dark:border-pink-500",
      "lg:dark:border-pink-600",
      "lg:dark:border-pink-700",
      "lg:dark:border-pink-800",
      "lg:dark:border-pink-900",
    ],
    rose: [
      "lg:dark:border-rose-100",
      "lg:dark:border-rose-200",
      "lg:dark:border-rose-300",
      "lg:dark:border-rose-400",
      "lg:dark:border-rose-500",
      "lg:dark:border-rose-600",
      "lg:dark:border-rose-700",
      "lg:dark:border-rose-800",
      "lg:dark:border-rose-900",
    ],
  },
};
