export const variants = {
  base: {
    white: "md:dark:bg-white",
    black: "md:dark:bg-black",
    neutral: [
      "md:dark:bg-neutral-100",
      "md:dark:bg-neutral-200",
      "md:dark:bg-neutral-300",
      "md:dark:bg-neutral-400",
      "md:dark:bg-neutral-500",
      "md:dark:bg-neutral-600",
      "md:dark:bg-neutral-700",
      "md:dark:bg-neutral-800",
      "md:dark:bg-neutral-900",
    ],
    stone: [
      "md:dark:bg-stone-100",
      "md:dark:bg-stone-200",
      "md:dark:bg-stone-300",
      "md:dark:bg-stone-400",
      "md:dark:bg-stone-500",
      "md:dark:bg-stone-600",
      "md:dark:bg-stone-700",
      "md:dark:bg-stone-800",
      "md:dark:bg-stone-900",
    ],
    slate: [
      "md:dark:bg-slate-100",
      "md:dark:bg-slate-200",
      "md:dark:bg-slate-300",
      "md:dark:bg-slate-400",
      "md:dark:bg-slate-500",
      "md:dark:bg-slate-600",
      "md:dark:bg-slate-700",
      "md:dark:bg-slate-800",
      "md:dark:bg-slate-900",
    ],
    gray: [
      "md:dark:bg-gray-100",
      "md:dark:bg-gray-200",
      "md:dark:bg-gray-300",
      "md:dark:bg-gray-400",
      "md:dark:bg-gray-500",
      "md:dark:bg-gray-600",
      "md:dark:bg-gray-700",
      "md:dark:bg-gray-800",
      "md:dark:bg-gray-900",
    ],
    zinc: [
      "md:dark:bg-zinc-100",
      "md:dark:bg-zinc-200",
      "md:dark:bg-zinc-300",
      "md:dark:bg-zinc-400",
      "md:dark:bg-zinc-500",
      "md:dark:bg-zinc-600",
      "md:dark:bg-zinc-700",
      "md:dark:bg-zinc-800",
      "md:dark:bg-zinc-900",
    ],
    red: [
      "md:dark:bg-red-100",
      "md:dark:bg-red-200",
      "md:dark:bg-red-300",
      "md:dark:bg-red-400",
      "md:dark:bg-red-500",
      "md:dark:bg-red-600",
      "md:dark:bg-red-700",
      "md:dark:bg-red-800",
      "md:dark:bg-red-900",
    ],
    orange: [
      "md:dark:bg-orange-100",
      "md:dark:bg-orange-200",
      "md:dark:bg-orange-300",
      "md:dark:bg-orange-400",
      "md:dark:bg-orange-500",
      "md:dark:bg-orange-600",
      "md:dark:bg-orange-700",
      "md:dark:bg-orange-800",
      "md:dark:bg-orange-900",
    ],
    amber: [
      "md:dark:bg-amber-100",
      "md:dark:bg-amber-200",
      "md:dark:bg-amber-300",
      "md:dark:bg-amber-400",
      "md:dark:bg-amber-500",
      "md:dark:bg-amber-600",
      "md:dark:bg-amber-700",
      "md:dark:bg-amber-800",
      "md:dark:bg-amber-900",
    ],
    yellow: [
      "md:dark:bg-yellow-100",
      "md:dark:bg-yellow-200",
      "md:dark:bg-yellow-300",
      "md:dark:bg-yellow-400",
      "md:dark:bg-yellow-500",
      "md:dark:bg-yellow-600",
      "md:dark:bg-yellow-700",
      "md:dark:bg-yellow-800",
      "md:dark:bg-yellow-900",
    ],
    lime: [
      "md:dark:bg-lime-100",
      "md:dark:bg-lime-200",
      "md:dark:bg-lime-300",
      "md:dark:bg-lime-400",
      "md:dark:bg-lime-500",
      "md:dark:bg-lime-600",
      "md:dark:bg-lime-700",
      "md:dark:bg-lime-800",
      "md:dark:bg-lime-900",
    ],
    green: [
      "md:dark:bg-green-100",
      "md:dark:bg-green-200",
      "md:dark:bg-green-300",
      "md:dark:bg-green-400",
      "md:dark:bg-green-500",
      "md:dark:bg-green-600",
      "md:dark:bg-green-700",
      "md:dark:bg-green-800",
      "md:dark:bg-green-900",
    ],
    emerald: [
      "md:dark:bg-emerald-100",
      "md:dark:bg-emerald-200",
      "md:dark:bg-emerald-300",
      "md:dark:bg-emerald-400",
      "md:dark:bg-emerald-500",
      "md:dark:bg-emerald-600",
      "md:dark:bg-emerald-700",
      "md:dark:bg-emerald-800",
      "md:dark:bg-emerald-900",
    ],
    teal: [
      "md:dark:bg-teal-100",
      "md:dark:bg-teal-200",
      "md:dark:bg-teal-300",
      "md:dark:bg-teal-400",
      "md:dark:bg-teal-500",
      "md:dark:bg-teal-600",
      "md:dark:bg-teal-700",
      "md:dark:bg-teal-800",
      "md:dark:bg-teal-900",
    ],
    cyan: [
      "md:dark:bg-cyan-100",
      "md:dark:bg-cyan-200",
      "md:dark:bg-cyan-300",
      "md:dark:bg-cyan-400",
      "md:dark:bg-cyan-500",
      "md:dark:bg-cyan-600",
      "md:dark:bg-cyan-700",
      "md:dark:bg-cyan-800",
      "md:dark:bg-cyan-900",
    ],
    sky: [
      "md:dark:bg-sky-100",
      "md:dark:bg-sky-200",
      "md:dark:bg-sky-300",
      "md:dark:bg-sky-400",
      "md:dark:bg-sky-500",
      "md:dark:bg-sky-600",
      "md:dark:bg-sky-700",
      "md:dark:bg-sky-800",
      "md:dark:bg-sky-900",
    ],
    blue: [
      "md:dark:bg-blue-100",
      "md:dark:bg-blue-200",
      "md:dark:bg-blue-300",
      "md:dark:bg-blue-400",
      "md:dark:bg-blue-500",
      "md:dark:bg-blue-600",
      "md:dark:bg-blue-700",
      "md:dark:bg-blue-800",
      "md:dark:bg-blue-900",
    ],
    indigo: [
      "md:dark:bg-indigo-100",
      "md:dark:bg-indigo-200",
      "md:dark:bg-indigo-300",
      "md:dark:bg-indigo-400",
      "md:dark:bg-indigo-500",
      "md:dark:bg-indigo-600",
      "md:dark:bg-indigo-700",
      "md:dark:bg-indigo-800",
      "md:dark:bg-indigo-900",
    ],
    violet: [
      "md:dark:bg-violet-100",
      "md:dark:bg-violet-200",
      "md:dark:bg-violet-300",
      "md:dark:bg-violet-400",
      "md:dark:bg-violet-500",
      "md:dark:bg-violet-600",
      "md:dark:bg-violet-700",
      "md:dark:bg-violet-800",
      "md:dark:bg-violet-900",
    ],
    purple: [
      "md:dark:bg-purple-100",
      "md:dark:bg-purple-200",
      "md:dark:bg-purple-300",
      "md:dark:bg-purple-400",
      "md:dark:bg-purple-500",
      "md:dark:bg-purple-600",
      "md:dark:bg-purple-700",
      "md:dark:bg-purple-800",
      "md:dark:bg-purple-900",
    ],
    fuchsia: [
      "md:dark:bg-fuchsia-100",
      "md:dark:bg-fuchsia-200",
      "md:dark:bg-fuchsia-300",
      "md:dark:bg-fuchsia-400",
      "md:dark:bg-fuchsia-500",
      "md:dark:bg-fuchsia-600",
      "md:dark:bg-fuchsia-700",
      "md:dark:bg-fuchsia-800",
      "md:dark:bg-fuchsia-900",
    ],
    pink: [
      "md:dark:bg-pink-100",
      "md:dark:bg-pink-200",
      "md:dark:bg-pink-300",
      "md:dark:bg-pink-400",
      "md:dark:bg-pink-500",
      "md:dark:bg-pink-600",
      "md:dark:bg-pink-700",
      "md:dark:bg-pink-800",
      "md:dark:bg-pink-900",
    ],
    rose: [
      "md:dark:bg-rose-100",
      "md:dark:bg-rose-200",
      "md:dark:bg-rose-300",
      "md:dark:bg-rose-400",
      "md:dark:bg-rose-500",
      "md:dark:bg-rose-600",
      "md:dark:bg-rose-700",
      "md:dark:bg-rose-800",
      "md:dark:bg-rose-900",
    ],
  },
};
