import { css } from "styled-system/css";

export const s = {
  sidebar: css({
    display: "flex",
    flexDirection: "column",
    width: "220px",
    minHeight: "100vh",
    backgroundColor: "#0D0D1A",
    borderRight: "1px solid #1E1E2E",
    paddingY: "6",
    flexShrink: "0",
  }),
  logo: css({
    display: "flex",
    alignItems: "center",
    gap: "2",
    paddingX: "5",
    marginBottom: "6",
  }),
  logoIcon: css({
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    backgroundColor: "#3B82F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "sm",
    fontWeight: "700",
    color: "white",
    flexShrink: "0",
  }),
  logoText: css({
    fontSize: "base",
    fontWeight: "700",
    color: "#F1F5F9",
    letterSpacing: "-0.01em",
  }),
  nav: css({
    flex: "1",
    display: "flex",
    flexDirection: "column",
    gap: "1",
    paddingX: "3",
  }),
  sectionLabel: css({
    fontSize: "xs",
    fontWeight: "600",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    paddingX: "2",
    paddingTop: "4",
    paddingBottom: "1",
  }),
  navItem: css({
    display: "flex",
    alignItems: "center",
    gap: "2.5",
    paddingX: "3",
    paddingY: "2",
    borderRadius: "8px",
    fontSize: "sm",
    fontWeight: "500",
    color: "#64748B",
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.15s",
    _hover: { backgroundColor: "#1C1C27", color: "#E2E8F0" },
  }),
  navItemActive: css({
    backgroundColor: "#1C1C27",
    color: "#E2E8F0",
  }),
  navItemAccent: css({
    backgroundColor: "rgba(59,130,246,0.1)",
    color: "#3B82F6",
    _hover: { backgroundColor: "rgba(59,130,246,0.15)", color: "#3B82F6" },
  }),
  userCard: css({
    marginX: "3",
    marginTop: "4",
    paddingX: "3",
    paddingY: "3",
    borderRadius: "10px",
    backgroundColor: "#1C1C27",
    display: "flex",
    alignItems: "center",
    gap: "3",
    borderTop: "1px solid #1E1E2E",
  }),
  avatar: css({
    width: "32px",
    height: "32px",
    borderRadius: "full",
    backgroundColor: "#3B82F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "sm",
    fontWeight: "700",
    color: "white",
    flexShrink: "0",
  }),
  userName: css({
    fontSize: "sm",
    fontWeight: "600",
    color: "#E2E8F0",
    lineHeight: "1.2",
  }),
  userEmail: css({
    fontSize: "xs",
    color: "#64748B",
    lineHeight: "1.2",
  }),
};
