export const variants = {
  base: [
    "opacity-100",
    "opacity-90",
    "opacity-80",
    "opacity-70",
    "opacity-60",
    "opacity-50",
    "opacity-40",
    "opacity-30",
    "opacity-20",
    "opacity-10",
    "opacity-0",
  ],
  medium: [
    "md:opacity-100",
    "md:opacity-90",
    "md:opacity-80",
    "md:opacity-70",
    "md:opacity-60",
    "md:opacity-50",
    "md:opacity-40",
    "md:opacity-30",
    "md:opacity-20",
    "md:opacity-10",
    "md:opacity-0",
  ],
  large: [
    "lg:opacity-100",
    "lg:opacity-90",
    "lg:opacity-80",
    "lg:opacity-70",
    "lg:opacity-60",
    "lg:opacity-50",
    "lg:opacity-40",
    "lg:opacity-30",
    "lg:opacity-20",
    "lg:opacity-10",
    "lg:opacity-0",
  ],
};
