export const variants = {
  utils: "select-none",
  base: {
    size: [
      "text-xs",
      "text-sm",
      "text-base",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "text-6xl",
      "text-7xl",
      "text-8xl",
      "text-9xl",
    ],
    weight: [
      "font-thin",
      "font-extralight",
      "font-light",
      "font-normal",
      "font-medium",
      "font-semibold",
      "font-bold",
      "font-extrabold",
      "font-black",
    ],
    wrap: ["text-wrap", "text-nowrap", "text-balance", "text-pretty"],
  },
  medium: {
    size: [
      "md:text-xs",
      "md:text-sm",
      "md:text-base",
      "md:text-lg",
      "md:text-xl",
      "md:text-2xl",
      "md:text-3xl",
      "md:text-4xl",
      "md:text-5xl",
      "md:text-6xl",
      "md:text-7xl",
      "md:text-8xl",
      "md:text-9xl",
    ],
    weight: [
      "md:font-thin",
      "md:font-extralight",
      "md:font-light",
      "md:font-normal",
      "md:font-medium",
      "md:font-semibold",
      "md:font-bold",
      "md:font-extrabold",
      "md:font-black",
    ],
    wrap: [
      "md:text-wrap",
      "md:text-nowrap",
      "md:text-balance",
      "md:text-pretty",
    ],
  },
  large: {
    size: [
      "lg:text-xs",
      "lg:text-sm",
      "lg:text-base",
      "lg:text-lg",
      "lg:text-xl",
      "lg:text-2xl",
      "lg:text-3xl",
      "lg:text-4xl",
      "lg:text-5xl",
      "lg:text-6xl",
      "md:text-7xl",
      "md:text-8xl",
      "md:text-9xl",
    ],
    weight: [
      "lg:font-thin",
      "lg:font-extralight",
      "lg:font-light",
      "lg:font-normal",
      "lg:font-medium",
      "lg:font-semibold",
      "lg:font-bold",
      "lg:font-extrabold",
      "lg:font-black",
    ],
    wrap: [
      "lg:text-wrap",
      "lg:text-nowrap",
      "lg:text-balance",
      "lg:text-pretty",
    ],
  },
};
