export const variants = {
  base: {
    white: "dark:text-white",
    black: "dark:text-black",
    neutral: [
      "dark:text-neutral-100",
      "dark:text-neutral-200",
      "dark:text-neutral-300",
      "dark:text-neutral-400",
      "dark:text-neutral-500",
      "dark:text-neutral-600",
      "dark:text-neutral-700",
      "dark:text-neutral-800",
      "dark:text-neutral-900",
    ],
    stone: [
      "dark:text-stone-100",
      "dark:text-stone-200",
      "dark:text-stone-300",
      "dark:text-stone-400",
      "dark:text-stone-500",
      "dark:text-stone-600",
      "dark:text-stone-700",
      "dark:text-stone-800",
      "dark:text-stone-900",
    ],
    slate: [
      "dark:text-slate-100",
      "dark:text-slate-200",
      "dark:text-slate-300",
      "dark:text-slate-400",
      "dark:text-slate-500",
      "dark:text-slate-600",
      "dark:text-slate-700",
      "dark:text-slate-800",
      "dark:text-slate-900",
    ],
    gray: [
      "dark:text-gray-100",
      "dark:text-gray-200",
      "dark:text-gray-300",
      "dark:text-gray-400",
      "dark:text-gray-500",
      "dark:text-gray-600",
      "dark:text-gray-700",
      "dark:text-gray-800",
      "dark:text-gray-900",
    ],
    zinc: [
      "dark:text-zinc-100",
      "dark:text-zinc-200",
      "dark:text-zinc-300",
      "dark:text-zinc-400",
      "dark:text-zinc-500",
      "dark:text-zinc-600",
      "dark:text-zinc-700",
      "dark:text-zinc-800",
      "dark:text-zinc-900",
    ],
    red: [
      "dark:text-red-100",
      "dark:text-red-200",
      "dark:text-red-300",
      "dark:text-red-400",
      "dark:text-red-500",
      "dark:text-red-600",
      "dark:text-red-700",
      "dark:text-red-800",
      "dark:text-red-900",
    ],
    orange: [
      "dark:text-orange-100",
      "dark:text-orange-200",
      "dark:text-orange-300",
      "dark:text-orange-400",
      "dark:text-orange-500",
      "dark:text-orange-600",
      "dark:text-orange-700",
      "dark:text-orange-800",
      "dark:text-orange-900",
    ],
    amber: [
      "dark:text-amber-100",
      "dark:text-amber-200",
      "dark:text-amber-300",
      "dark:text-amber-400",
      "dark:text-amber-500",
      "dark:text-amber-600",
      "dark:text-amber-700",
      "dark:text-amber-800",
      "dark:text-amber-900",
    ],
    yellow: [
      "dark:text-yellow-100",
      "dark:text-yellow-200",
      "dark:text-yellow-300",
      "dark:text-yellow-400",
      "dark:text-yellow-500",
      "dark:text-yellow-600",
      "dark:text-yellow-700",
      "dark:text-yellow-800",
      "dark:text-yellow-900",
    ],
    lime: [
      "dark:text-lime-100",
      "dark:text-lime-200",
      "dark:text-lime-300",
      "dark:text-lime-400",
      "dark:text-lime-500",
      "dark:text-lime-600",
      "dark:text-lime-700",
      "dark:text-lime-800",
      "dark:text-lime-900",
    ],
    green: [
      "dark:text-green-100",
      "dark:text-green-200",
      "dark:text-green-300",
      "dark:text-green-400",
      "dark:text-green-500",
      "dark:text-green-600",
      "dark:text-green-700",
      "dark:text-green-800",
      "dark:text-green-900",
    ],
    emerald: [
      "dark:text-emerald-100",
      "dark:text-emerald-200",
      "dark:text-emerald-300",
      "dark:text-emerald-400",
      "dark:text-emerald-500",
      "dark:text-emerald-600",
      "dark:text-emerald-700",
      "dark:text-emerald-800",
      "dark:text-emerald-900",
    ],
    teal: [
      "dark:text-teal-100",
      "dark:text-teal-200",
      "dark:text-teal-300",
      "dark:text-teal-400",
      "dark:text-teal-500",
      "dark:text-teal-600",
      "dark:text-teal-700",
      "dark:text-teal-800",
      "dark:text-teal-900",
    ],
    cyan: [
      "dark:text-cyan-100",
      "dark:text-cyan-200",
      "dark:text-cyan-300",
      "dark:text-cyan-400",
      "dark:text-cyan-500",
      "dark:text-cyan-600",
      "dark:text-cyan-700",
      "dark:text-cyan-800",
      "dark:text-cyan-900",
    ],
    sky: [
      "dark:text-sky-100",
      "dark:text-sky-200",
      "dark:text-sky-300",
      "dark:text-sky-400",
      "dark:text-sky-500",
      "dark:text-sky-600",
      "dark:text-sky-700",
      "dark:text-sky-800",
      "dark:text-sky-900",
    ],
    blue: [
      "dark:text-blue-100",
      "dark:text-blue-200",
      "dark:text-blue-300",
      "dark:text-blue-400",
      "dark:text-blue-500",
      "dark:text-blue-600",
      "dark:text-blue-700",
      "dark:text-blue-800",
      "dark:text-blue-900",
    ],
    indigo: [
      "dark:text-indigo-100",
      "dark:text-indigo-200",
      "dark:text-indigo-300",
      "dark:text-indigo-400",
      "dark:text-indigo-500",
      "dark:text-indigo-600",
      "dark:text-indigo-700",
      "dark:text-indigo-800",
      "dark:text-indigo-900",
    ],
    violet: [
      "dark:text-violet-100",
      "dark:text-violet-200",
      "dark:text-violet-300",
      "dark:text-violet-400",
      "dark:text-violet-500",
      "dark:text-violet-600",
      "dark:text-violet-700",
      "dark:text-violet-800",
      "dark:text-violet-900",
    ],
    purple: [
      "dark:text-purple-100",
      "dark:text-purple-200",
      "dark:text-purple-300",
      "dark:text-purple-400",
      "dark:text-purple-500",
      "dark:text-purple-600",
      "dark:text-purple-700",
      "dark:text-purple-800",
      "dark:text-purple-900",
    ],
    fuchsia: [
      "dark:text-fuchsia-100",
      "dark:text-fuchsia-200",
      "dark:text-fuchsia-300",
      "dark:text-fuchsia-400",
      "dark:text-fuchsia-500",
      "dark:text-fuchsia-600",
      "dark:text-fuchsia-700",
      "dark:text-fuchsia-800",
      "dark:text-fuchsia-900",
    ],
    pink: [
      "dark:text-pink-100",
      "dark:text-pink-200",
      "dark:text-pink-300",
      "dark:text-pink-400",
      "dark:text-pink-500",
      "dark:text-pink-600",
      "dark:text-pink-700",
      "dark:text-pink-800",
      "dark:text-pink-900",
    ],
    rose: [
      "dark:text-rose-100",
      "dark:text-rose-200",
      "dark:text-rose-300",
      "dark:text-rose-400",
      "dark:text-rose-500",
      "dark:text-rose-600",
      "dark:text-rose-700",
      "dark:text-rose-800",
      "dark:text-rose-900",
    ],
  },
};
