name: pull request
on:
  pull_request:
    branches: [main]
    types: [labeled, opened, synchronize]

env:
  TITLE: ${{ github.event.pull_request.title }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v1
      - run: bun i
      - run: bun test app
